### ISSUE TITLE
Running Installed Applications

### ISSUE THREAD

**Issue by Skamikazzze** [Rajkumrdusad/Tool-X#22]
Hello, @Rajkumrdusad
How to run applications installed in tool-x in termux? Solution of #13 does not fit. Thanx!

**Comment by Skamikazzze** [comment]
Understood. You can close.

**Comment by Rajkumrdusad** [comment]
If any problem or query so please inform us thanks..

**Comment by whytehealer** [comment]
Hello, @Rajkumrdusad
How to run applications installed in tool-x in termux? Solution

**Comment by Rajkumrdusad** [comment]
Hey @whytehealer its very simple process.
For example you are installed IP-Tracer and you want to run it.
so use following command :-
For go to home directory because all the tools installed on home directory.
$ cd ~/
for list all directory and file
$ ls
if there are IP-Tracer directory that means tool is installed. Go to IP-Tracer directory
$ cd IP-Tracer
$ sh install

To trace ip type 
$ trace -t <ip_address>

All tools have different process for run that tools. each tool have different process you can not follow any one process. I hope you will understand please ask if any problem we are happy to help you.

**Comment by whytehealer** [comment]
And what of wpscan

**Comment by Rajkumrdusad** [comment]
When you install any tool from tool-x it will show the instruction how to run that tool.
But if you don't know here the command :-
$ cd wpscan
$ ruby wpscan.rb

**Comment by whytehealer** [comment]
Thanks

**Comment by Bobbie916** [comment]
> When you install any tool from tool-x it will show the instruction how to run that tool.
> But if you don't know here the command :-
> $ cd wpscan
> $ ruby wpscan.rb

Can you make a list of how to run each application and what the run command would be ?
