### ISSUE TITLE
Pleas help

### ISSUE THREAD

**Issue by okakrisna** [Rajkumrdusad/Tool-X#23]
i installed Tool-X successfully on android. after installing i dont know how to start the programs i want to maybe e.g. reaver. wifite or something else. so can anyone explain me how i can start the tools.

**Comment by Rajkumrdusad** [comment]
Hey @okakrisna its very simple to start any tool in termux.
First you have to install a tool witch you want to use for e.g wifite
When you install it Tool-X is show how to open this tool but if don't know it tell you.
Note : all the tools are installed on home directory.
Go to home directory type :
1) cd 
Now see installed tools type : 
2) ls
if there are wifite directory that mens wifite is installed
Go to wifite directory : 
3) cd wifite
To see all the files of wifite type : 
4) ls
To run wifite type : 
4) python wifite.py

I hope it will help if any question so please tell us..
We are happy to help you..

**Comment by okakrisna** [comment]
already, but it's written "can't open the file 'airgeddon.py': [Errno 2] There are no files or directories like that"

**Comment by Rajkumrdusad** [comment]
Yes because there are airgeddon is not installed or you are not following all the steps.
for run any tool you have to follow some steps : 
1) Go to Home directory because all the tools are installed on home e.g. type cd or cd ~/ to got home directory
2) see all the directory of home if there are directory like your tool name e.g airgeddon that mens tool is installed. e.g. type ls to see all the directory 
3) Go to tool directory e.g. cd airgeddion 
4) see all the directory and files of your tool e.g type ls
5) run the tool script e.g. python airgeddion.py

Its very simple process i hope you will easly understand..

**Comment by okakrisna** [comment]
I installed all the tools, and followed all the steps, but the results are still the same

**Comment by Rajkumrdusad** [comment]
I dont know why the error if you installed airgeddon because error is you have not installed airgeddon so please install it..

**Comment by Rajkumrdusad** [comment]
If are you try to run airgeddon why you are using python airgeddin.py it wrong airgeddon is not python script.
Try : 
$ bash airgeddon.sh
It will work

**Comment by okakrisna** [comment]
ok it works, but the other tools are using $ bash.sh too? or python?

**Comment by Rajkumrdusad** [comment]
you can identify them using their extainson like bash or sh file are end with .sh and python files are end with .py and lost or other extainsons are there.

**Comment by okakrisna** [comment]
ok thank you for the time bro

**Comment by Rajkumrdusad** [comment]
welcome bro..
