### ISSUE TITLE
"0" input not available 

### ISSUE THREAD

**Issue by Kqiden** [Rajkumrdusad/Tool-X#50]
Hello,

I've just installed Tool-X and noticed that option "0" to install all commands isn't available, I also can't install them one by one.

Can you please inform me on how to install the commands and tools please. 

Thank you.

**Comment by JavaSergo** [comment]
Hey, bro, see, it was exactly as you want week ago, today new version and
the install process changed, I also do it one by one , in 1st very, was 264
tools, and know it more than 300, but I am not creator, I am user like you
maybe have many less experience that you, we must ask it from creator on
GitHub, .
Line with clone..... GitHub. Com this address of this page on GitHub, this
guy know all bugs, and how it works, I installed all in one action, .. take
one hour +-, after it. Was with few options, of op sys, I've chosen Termux
Os, today I see the update and post it, but I still looking for some
information, how, what new, how it work, because, untill today, I don't try
anything, because, go-to directory of... For example airmon ng, and do this
and this, I didn't , I can't to do simple operation, Go-to folder, because
it starting install in . Loops

сб, 7 дек. 2019 г., 5:47 Kqiden <notifications@github.com>:

**Comment by JavaSergo** [comment]
I see you here , hhh ))), we need to ask at author

**Comment by JavaSergo** [comment]
Dear author, can you explain to me and other friend, how we use you tool

**Comment by Rajkumrdusad** [comment]
Yaa why not i will explain everything about this new update. now in this update v2.1 there are no any option to install all tools on single click its removed because in tool-x there are more then 350+ tools and its very difficult to install more then 300 tools in android its create some problem like storage and lost of other. now we remove Termux os but it will available in tools category in some days. we are trying to make things more easy to use but if there are any issu so help us to make things easy.

**Comment by Kqiden** [comment]
I'm on Kali Linux 2019.4. Can you tell me how to install them one by one then please?

**Comment by Rajkumrdusad** [comment]
Yes you can install then one by one you have to select
1 ] show all tools 
Then enter the number of tool that you want to install. if any issue so please inform us..

**Comment by Kqiden** [comment]
Yes i have tried that it just comes up with "?? tool not installed"

**Comment by Rajkumrdusad** [comment]
ok may be there are some error. please tell me the number of tool when it says tool not installed !!

**Comment by Kqiden** [comment]
its all the tools, none of them can be installed

**Comment by grufty47** [comment]
Installed Tool-X successfully a week ago under termux on Galaxy S 8. Though Tool-X can now be installed in my Android Mi A2 lite but it only lists the 350+ modules, none e.g. #326 termux-ubuntu can be selected for installation (correctly). I am sorry to say that the installation guide appears not be correct, at least, as before default modules (termux-ubuntu) cannot be selected to be correctly installed. Are additional modules (wget?) to be loaded or changes in resolve.conf required? The title still says Tool-X 2.0 instead of Tool-X 2.1, 350+ modules are listed, however no selection or installation menu. please have a look into it (as already indicated). Thanks.

**Comment by Rajkumrdusad** [comment]
Ok try to update tool-x or uninstall tool-x and re-install it. I hope it will work for you.
For uninstall tool-x type rm -T command on tool-x prompt.

**Comment by grufty47** [comment]
Thanks a lot for your rapid answer . I attempted it anew ... and succeeded
though with discrepancies to your Guide. I did not get to the " 0-5, x "
multiple choice menu but could half way install <326, termux-ubuntu>, from
the "list" menu. However, <pkg install wget proot> needed to be installed
to eventually arrive to install termux-ubuntu with <./ubuntu.sh> i.s.o
start termux-ubuntu or alike, Re Screenshots.
Please allow 2 questions:
At the moment my device is Magisk rooted, If removed, does Tool-X or
termux- Ubuntu cause root also?
Why can I not Access the /Dev folder (I Need Access to the boot
Files/partitions without rooting the system).
Many thanks for your Help!
Grufty47 / Jochen Drake


Rajkumar Dusad <notifications@github.com> schrieb am Mo., 9. Dez. 2019,
03:33:

**Comment by Rajkumrdusad** [comment]
Thank you @grufty47 / Jochen Drake.
you need to unstall wget and proot to install termux-ubuntu sorry for that we will fix it as soon as possible.
Your answers :
1) if you remove root, tool-x and termux-ubuntu will run as it is. Tool-X and termux-ubuntu does not require any root.
2) in linux system like Android /dev directory contain all device , driver and lost to special files. By Default you can not access /dev folder without root because you need root permission. without root you can't access it.

**Comment by sandeepcv** [comment]
I can't install tools from tool-x
![Screenshot_2020-05-01-08-48-48-273_com termux](https://user-images.githubusercontent.com/64625551/80779885-a3518d80-8b8a-11ea-9b5a-ba22fb30af49.jpg)

**Comment by rajkumardusad** [comment]
If you have rooted your device so try with su or tsu it will works.

**Comment by ShahrukhAbrar** [comment]
I am having the same problem. Unable to install any tool.
